### ISSUE TITLE
add INNER for join

### ISSUE THREAD

**Issue by GammaSquare** [okeeffdp/snowflake-sublime-text#3]
Hello,

We miss the keyword INNER for the join condition.

Thanks!

**Comment by okeeffdp** [comment]
@GammaSquare , I'll see what I can do. I spotted the same issue with the VSCode version

**Comment by GammaSquare** [comment]
Hi @okeeffdp! Let me know if the PR will resolve this issue. Let me know other files need an update for VSCode. Cheers!

**Comment by okeeffdp** [comment]
Thanks for the help with that. I have added you as a contributor.
